name: common

on:
  - push
  - workflow_dispatch

permissions: read-all

jobs:
  shellcheck:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix-shell --pure -p git shellcheck --run "git ls-files --exclude='*.sh' --ignored -c -z | xargs -0r shellcheck"

  find-git-merge-conflict-marker:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix-shell --pure -p git --run "(git grep -rnlP '[<]{7}.*' | xargs git grep -rnlP '[=]{7}.*' | xargs git grep -rnlP '[>]{7}.*') && exit 1 || exit 0"

  gitleaks:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix-shell --pure -p git gitleaks --run 'gitleaks detect --source . -v'

  osv-scanner:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix-shell --pure -p osv-scanner go --run 'osv-scanner scan source -r --no-ignore . ; EXITCODE=$? ; test $EXITCODE -eq 128 || exit $EXITCODE' || true

  dotenv:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix-shell --pure -p dotenv-linter --run 'dotenv-linter --skip QuoteCharacter --skip UnorderedKey'
